name: Build & Release InfluxDB3 Unlocked

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

env:
  CARGO_INCREMENTAL: "yes"
  CARGO_NET_GIT_FETCH_WITH_CLI: "false"
  PROFILE: "release"
  FEATURES: "aws,gcp,azure,jemalloc_replacing_malloc"
  PACKAGE: "influxdb3"
  PBS_DATE: "unset"
  PBS_VERSION: "unset"
  PBS_TARGET: "x86_64-unknown-linux-gnu"

jobs:
  build-binary:
    name: Build Binary
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: metrico/influxdb3-unlocked
          ref: unlocked

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y binutils build-essential curl pkg-config libssl-dev clang lld git patchelf protobuf-compiler zstd libz-dev python3-dev python3-pip

      - name: Build binary
        run: |
          cargo build --package="$PACKAGE" --profile="$PROFILE" --no-default-features --features="$FEATURES"
          objcopy --compress-debug-sections "target/$PROFILE/$PACKAGE"

      - name: Extract version
        run: |
          VERSION=$(./target/$PROFILE/$PACKAGE --version | cut -d' ' -f2 | cut -d',' -f1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Create release archive
        run: |
          mkdir -p release
          cp "./target/$PROFILE/$PACKAGE" release/influxdb3

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: influxdb3
          path: ./release/influxdb3
          retention-days: 1

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ./release/influxdb3
            
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: metrico/influxdb3-unlocked
          ref: unlocked

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: influxdb3
          path: ./binary

      - name: Log in to the GHCR registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Docker Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./docker/Dockerfile.prebuilt
          push: true
          tags: |
            ghcr.io/metrico/influxdb3-unlocked:latest
            ghcr.io/metrico/influxdb3-unlocked:${{ needs.build-binary.outputs.version }}
          build-args: |
            PACKAGE=influxdb3
          cache-from: type=gha
          cache-to: type=gha,mode=max 