name: Sync Upstream

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  sync-upstream:
    name: Sync with Upstream
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/influxdata/influxdb.git

      - name: Fetch upstream
        run: |
          git fetch upstream main

      - name: Create or reset upstream branch
        run: |
          # Delete upstream branch if it exists (locally or remotely)
          git branch -D upstream 2>/dev/null || true
          git push origin --delete upstream 2>/dev/null || true
          
          # Create new upstream branch from upstream/main
          git checkout -b upstream upstream/main

      - name: Push upstream branch
        run: |
          git push origin upstream --force

      - name: Cleanup
        run: |
          git remote remove upstream
